AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for AI Business Solutions

Resources:
  AIComputeInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      ImageId: ami-12345678  # Replace with actual AMI ID
      SecurityGroups:
        - Ref: AISecurityGroup
      Tags:
        - Key: Name
          Value: AI-Business-Compute

  AISecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for AI Business Solutions
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

